"""add owner_id to task_lists

Revision ID: 96db6509358c
Revises: 1ca39563377a
Create Date: 2025-06-22 08:32:50.625031

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96db6509358c"
down_revision: Union[str, Sequence[str], None] = "1ca39563377a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task_lists", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "task_lists", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task_lists", type_="foreignkey")
    op.drop_column("task_lists", "owner_id")
    # ### end Alembic commands ###
